# Generated by Django 2.1.5 on 2020-05-09 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20200507_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='webiste',
            new_name='website',
        ),
    ]
